"""Streamlit dashboard for YOLO Vahan Saarthi traffic results."""

from __future__ import annotations

import json
from pathlib import Path

import pandas as pd
import streamlit as st

DEFAULT_SUMMARY = Path("runs/track/traffic_summary.json")
DEFAULT_EVENTS = Path("runs/track/crossing_events.csv")
DEMO_SUMMARY = Path("demo/traffic_summary.json")
DEMO_EVENTS = Path("demo/crossing_events.csv")

st.set_page_config(page_title="YOLO Vahan Saarthi", page_icon="🚗", layout="wide")

st.title("🚗 YOLO Vahan Saarthi")
st.caption("Traffic intelligence dashboard — detection, tracking, IN/OUT counting and analytics")

summary_file = st.sidebar.text_input("Summary JSON", str(DEFAULT_SUMMARY))
events_file = st.sidebar.text_input("Events CSV", str(DEFAULT_EVENTS))

summary_path = Path(summary_file)
events_path = Path(events_file)

# Streamlit Community Cloud does not have the local files generated by the tracker.
# Fall back to a clearly labelled demo dataset so the deployed dashboard is useful.
using_demo = False
if not summary_path.exists():
    if DEMO_SUMMARY.exists():
        summary_path = DEMO_SUMMARY
        events_path = DEMO_EVENTS
        using_demo = True
    else:
        st.warning("No traffic summary found yet. Run the tracker locally first.")
        st.code("python src/tracking_counting.py --source traffic_sample.webm")
        st.stop()

with summary_path.open("r", encoding="utf-8") as file:
    summary = json.load(file)

counts_in = summary.get("counts_in", {})
counts_out = summary.get("counts_out", {})
total_in = summary.get("total_in", 0)
total_out = summary.get("total_out", 0)
total_crossed = summary.get("total_crossed", total_in + total_out)
peak_visible = summary.get("peak_visible", 0)
avg_rate = summary.get("average_vehicles_per_minute", 0.0)
duration_minutes = summary.get("duration_minutes", 0.0)
density = summary.get("peak_density", "UNKNOWN")

if using_demo:
    st.info("📌 Demo mode: showing bundled sample analytics. Run the tracker locally and point the sidebar to your generated results for real data.")

col1, col2, col3, col4 = st.columns(4)
col1.metric("Vehicles IN", total_in)
col2.metric("Vehicles OUT", total_out)
col3.metric("Total Crossed", total_crossed)
col4.metric("Peak Visible", peak_visible)

st.subheader("📊 Vehicle Flow")
classes = sorted(set(counts_in) | set(counts_out))
chart_data = pd.DataFrame(
    {
        "IN": [counts_in.get(name, 0) for name in classes],
        "OUT": [counts_out.get(name, 0) for name in classes],
    },
    index=[name.capitalize() for name in classes],
)
st.bar_chart(chart_data)

left, middle, right = st.columns(3)
with left:
    st.metric("Average vehicles/min", f"{avg_rate:.1f}")
with middle:
    st.metric("Peak traffic density", density)
with right:
    st.metric("Analysis duration", f"{duration_minutes:.2f} min")

if events_path.exists():
    st.subheader("📈 Crossing Events")
    events = pd.read_csv(events_path)
    if not events.empty and "time_seconds" in events.columns:
        events["minute"] = (events["time_seconds"] // 60).astype(int)
        per_minute = events.groupby("minute").size().rename("vehicles").to_frame()
        st.line_chart(per_minute)
        st.dataframe(events, use_container_width=True)
    elif events.empty:
        st.caption("No crossing events recorded.")
else:
    st.caption("Crossing event data is not available for this dataset.")

st.subheader("⬇️ Export")
col_a, col_b = st.columns(2)
with col_a:
    st.download_button(
        "Download summary JSON",
        data=json.dumps(summary, indent=2),
        file_name="traffic_summary.json",
        mime="application/json",
    )
with col_b:
    csv_data = events_path.read_text(encoding="utf-8") if events_path.exists() else ""
    st.download_button(
        "Download events CSV",
        data=csv_data,
        file_name="crossing_events.csv",
        mime="text/csv",
    )

st.caption("YOLO Vahan Saarthi • Streamlit dashboard")
